import { ChargingStation, ChargingNetwork, Vehicle, UserNotification, ChargingHistoryEntry } from '@/types';

export const MOCK_NETWORKS: ChargingNetwork[] = [
  {
    id: 'net-ionity',
    name: 'Ionity Ultra Fast',
    operator: 'Ionity GmbH',
    coverageCountries: ['United Kingdom', 'France', 'Germany', 'Spain', 'Italy'],
    stationCount: 2450,
    fastChargerCount: 9800,
    connectorTypes: ['CCS2'],
    maxPowerKw: 350,
    supportPhone: '+49 89 4141410',
    website: 'https://ionity.eu',
  },
  {
    id: 'net-supercharger',
    name: 'Tesla Supercharger',
    operator: 'Tesla Inc.',
    coverageCountries: ['United States', 'United Kingdom', 'France', 'Germany', 'Japan', 'India', 'UAE', 'Singapore', 'Australia'],
    stationCount: 55000,
    fastChargerCount: 220000,
    connectorTypes: ['NACS', 'CCS2'],
    maxPowerKw: 250,
    supportPhone: '+1 888 518 3752',
    website: 'https://tesla.com/supercharger',
  },
  {
    id: 'net-chargepoint',
    name: 'ChargePoint Global',
    operator: 'ChargePoint Network',
    coverageCountries: ['United States', 'United Kingdom', 'France', 'Germany', 'Australia'],
    stationCount: 32000,
    fastChargerCount: 110000,
    connectorTypes: ['CCS2', 'Type 2', 'NACS'],
    maxPowerKw: 150,
    supportPhone: '+1 888 758 4389',
    website: 'https://chargepoint.com',
  },
  {
    id: 'net-tatapower',
    name: 'Tata Power EZ Charge',
    operator: 'Tata Power Company Ltd',
    coverageCountries: ['India'],
    stationCount: 4500,
    fastChargerCount: 12000,
    connectorTypes: ['CCS2', 'Type 2'],
    maxPowerKw: 240,
    supportPhone: '+91 1800 209 5161',
    website: 'https://tatapower.com/ezcharge',
  },
  {
    id: 'net-zeon',
    name: 'Zeon Charging',
    operator: 'Zeon Networks',
    coverageCountries: ['India'],
    stationCount: 850,
    fastChargerCount: 2400,
    connectorTypes: ['CCS2'],
    maxPowerKw: 150,
    supportPhone: '+91 94440 01122',
    website: 'https://zeoncharging.com',
  },
  {
    id: 'net-shell',
    name: 'Shell Recharge',
    operator: 'Shell EV Mobility',
    coverageCountries: ['United Kingdom', 'France', 'United States', 'Singapore', 'UAE'],
    stationCount: 18000,
    fastChargerCount: 45000,
    connectorTypes: ['CCS2', 'Type 2', 'CHAdeMO'],
    maxPowerKw: 175,
    supportPhone: '+44 800 026 0004',
    website: 'https://shellrecharge.com',
  },
];

export const MOCK_STATIONS: ChargingStation[] = [
  {
    id: 'st-lon-01',
    name: 'Mayfair Ultra-Fast Power Hub',
    operator: 'Ionity Ultra Fast',
    networkId: 'net-ionity',
    latitude: 51.5074,
    longitude: -0.1278,
    country: 'United Kingdom',
    city: 'London',
    address: '42 Park Lane, Mayfair, London W1K 7JA',
    openingHours: '24/7 Open',
    status: 'AVAILABLE',
    amenities: ['Coffee Shop', 'Free WiFi', 'Restrooms', 'EV Lounge', 'Valet'],
    rating: 4.9,
    reviewsCount: 142,
    dataSource: 'LIVE',
    providerName: 'OpenChargeMap API Adapter',
    lastUpdated: '2 min ago',
    connectors: [
      { id: 'c-lon-1', stationId: 'st-lon-01', type: 'CCS2', powerKw: 350, status: 'AVAILABLE', pricePerKwh: 0.69, currency: 'GBP' },
      { id: 'c-lon-2', stationId: 'st-lon-01', type: 'CCS2', powerKw: 350, status: 'AVAILABLE', pricePerKwh: 0.69, currency: 'GBP' },
      { id: 'c-lon-3', stationId: 'st-lon-01', type: 'CCS2', powerKw: 150, status: 'BUSY', pricePerKwh: 0.59, currency: 'GBP' },
      { id: 'c-lon-4', stationId: 'st-lon-01', type: 'Type 2', powerKw: 22, status: 'AVAILABLE', pricePerKwh: 0.35, currency: 'GBP' },
    ],
  },
  {
    id: 'st-lon-02',
    name: 'Westminster Supercharge Terminal',
    operator: 'Tesla Supercharger',
    networkId: 'net-supercharger',
    latitude: 51.4995,
    longitude: -0.1333,
    country: 'United Kingdom',
    city: 'London',
    address: 'Victoria Street, Westminster, London SW1E 5ND',
    openingHours: '24/7 Open',
    status: 'BUSY',
    amenities: ['Supermarket', 'Coffee Shop', 'Restrooms', 'ATM'],
    rating: 4.8,
    reviewsCount: 289,
    dataSource: 'LIVE',
    providerName: 'Tesla Network Adapter',
    lastUpdated: '1 min ago',
    connectors: [
      { id: 'c-lon-5', stationId: 'st-lon-02', type: 'CCS2', powerKw: 250, status: 'BUSY', pricePerKwh: 0.54, currency: 'GBP' },
      { id: 'c-lon-6', stationId: 'st-lon-02', type: 'NACS', powerKw: 250, status: 'BUSY', pricePerKwh: 0.54, currency: 'GBP' },
      { id: 'c-lon-7', stationId: 'st-lon-02', type: 'CCS2', powerKw: 250, status: 'AVAILABLE', pricePerKwh: 0.54, currency: 'GBP' },
      { id: 'c-lon-8', stationId: 'st-lon-02', type: 'CCS2', powerKw: 250, status: 'OUT_OF_SERVICE', pricePerKwh: 0.54, currency: 'GBP' },
    ],
  },
  {
    id: 'st-dxb-01',
    name: 'Downtown Dubai Mall Energy Plaza',
    operator: 'Tesla Supercharger',
    networkId: 'net-supercharger',
    latitude: 25.1972,
    longitude: 55.2744,
    country: 'United Arab Emirates',
    city: 'Dubai',
    address: 'Financial Center Rd, Downtown Dubai',
    openingHours: '24/7 Open',
    status: 'AVAILABLE',
    amenities: ['Luxury Lounge', 'Fine Dining', 'WiFi', 'Air Conditioned Waiting Area', 'Prayer Room'],
    rating: 5.0,
    reviewsCount: 310,
    dataSource: 'LIVE',
    providerName: 'DEWA Green Charger Sync Adapter',
    lastUpdated: 'Just now',
    connectors: [
      { id: 'c-dxb-1', stationId: 'st-dxb-01', type: 'CCS2', powerKw: 250, status: 'AVAILABLE', pricePerKwh: 1.25, currency: 'AED' },
      { id: 'c-dxb-2', stationId: 'st-dxb-01', type: 'CCS2', powerKw: 250, status: 'AVAILABLE', pricePerKwh: 1.25, currency: 'AED' },
      { id: 'c-dxb-3', stationId: 'st-dxb-01', type: 'NACS', powerKw: 250, status: 'AVAILABLE', pricePerKwh: 1.25, currency: 'AED' },
      { id: 'c-dxb-4', stationId: 'st-dxb-01', type: 'Type 2', powerKw: 43, status: 'AVAILABLE', pricePerKwh: 0.85, currency: 'AED' },
    ],
  },
  {
    id: 'st-che-01',
    name: 'Guindy Industrial Tech Charging Hub',
    operator: 'Zeon Charging',
    networkId: 'net-zeon',
    latitude: 13.0067,
    longitude: 80.2020,
    country: 'India',
    city: 'Chennai',
    address: 'Guindy Industrial Estate, Ekkattuthangal, Chennai 600032',
    openingHours: '24/7 Open',
    status: 'AVAILABLE',
    amenities: ['Café', 'Air Conditioned Lounge', 'Restrooms', '24/7 Security'],
    rating: 4.8,
    reviewsCount: 96,
    dataSource: 'LIVE',
    providerName: 'Zeon Provider Adapter',
    lastUpdated: '3 min ago',
    connectors: [
      { id: 'c-che-1', stationId: 'st-che-01', type: 'CCS2', powerKw: 150, status: 'AVAILABLE', pricePerKwh: 21.00, currency: 'INR' },
      { id: 'c-che-2', stationId: 'st-che-01', type: 'CCS2', powerKw: 150, status: 'AVAILABLE', pricePerKwh: 21.00, currency: 'INR' },
      { id: 'c-che-3', stationId: 'st-che-01', type: 'CCS2', powerKw: 60, status: 'BUSY', pricePerKwh: 18.50, currency: 'INR' },
      { id: 'c-che-4', stationId: 'st-che-01', type: 'Type 2', powerKw: 22, status: 'AVAILABLE', pricePerKwh: 12.00, currency: 'INR' },
    ],
  },
  {
    id: 'st-che-02',
    name: 'OMR IT Expressway EZ Charge Station',
    operator: 'Tata Power EZ Charge',
    networkId: 'net-tatapower',
    latitude: 12.9226,
    longitude: 80.2312,
    country: 'India',
    city: 'Chennai',
    address: 'Rajiv Gandhi Salai, Sholinganallur, Chennai 600119',
    openingHours: '06:00 - 23:00',
    status: 'AVAILABLE',
    amenities: ['Restaurant', 'Restroom', 'Snack Vending'],
    rating: 4.7,
    reviewsCount: 114,
    dataSource: 'DEMO',
    providerName: 'NOVA Simulated Provider Adapter',
    lastUpdated: 'Simulated 5 min ago',
    connectors: [
      { id: 'c-che-5', stationId: 'st-che-02', type: 'CCS2', powerKw: 120, status: 'AVAILABLE', pricePerKwh: 19.50, currency: 'INR' },
      { id: 'c-che-6', stationId: 'st-che-02', type: 'CCS2', powerKw: 60, status: 'AVAILABLE', pricePerKwh: 17.50, currency: 'INR' },
      { id: 'c-che-7', stationId: 'st-che-02', type: 'Type 2', powerKw: 22, status: 'AVAILABLE', pricePerKwh: 11.50, currency: 'INR' },
    ],
  },
  {
    id: 'st-par-01',
    name: 'Champs-Élysées Grand Power Hub',
    operator: 'Ionity Ultra Fast',
    networkId: 'net-ionity',
    latitude: 48.8698,
    longitude: 2.3075,
    country: 'France',
    city: 'Paris',
    address: 'Av. des Champs-Élysées 75008 Paris',
    openingHours: '24/7 Open',
    status: 'AVAILABLE',
    amenities: ['Boutique Café', 'WiFi', 'Covered Bay', 'Restrooms'],
    rating: 4.9,
    reviewsCount: 204,
    dataSource: 'LIVE',
    providerName: 'Ionity Sync Adapter',
    lastUpdated: '1 min ago',
    connectors: [
      { id: 'c-par-1', stationId: 'st-par-01', type: 'CCS2', powerKw: 350, status: 'AVAILABLE', pricePerKwh: 0.75, currency: 'EUR' },
      { id: 'c-par-2', stationId: 'st-par-01', type: 'CCS2', powerKw: 350, status: 'AVAILABLE', pricePerKwh: 0.75, currency: 'EUR' },
      { id: 'c-par-3', stationId: 'st-par-01', type: 'CCS2', powerKw: 150, status: 'BUSY', pricePerKwh: 0.65, currency: 'EUR' },
    ],
  },
  {
    id: 'st-sgp-01',
    name: 'Marina Bay Sands Clean Energy Hub',
    operator: 'Shell Recharge',
    networkId: 'net-shell',
    latitude: 1.2834,
    longitude: 103.8607,
    country: 'Singapore',
    city: 'Singapore',
    address: '10 Bayfront Ave, Singapore 018956',
    openingHours: '24/7 Open',
    status: 'AVAILABLE',
    amenities: ['Luxury Shopping', 'Supermarket', 'High-Speed WiFi', 'EV Lounge'],
    rating: 4.95,
    reviewsCount: 178,
    dataSource: 'LIVE',
    providerName: 'Shell Recharge API Adapter',
    lastUpdated: 'Just now',
    connectors: [
      { id: 'c-sgp-1', stationId: 'st-sgp-01', type: 'CCS2', powerKw: 180, status: 'AVAILABLE', pricePerKwh: 0.58, currency: 'SGD' },
      { id: 'c-sgp-2', stationId: 'st-sgp-01', type: 'CCS2', powerKw: 180, status: 'AVAILABLE', pricePerKwh: 0.58, currency: 'SGD' },
      { id: 'c-sgp-3', stationId: 'st-sgp-01', type: 'Type 2', powerKw: 43, status: 'AVAILABLE', pricePerKwh: 0.42, currency: 'SGD' },
    ],
  },
  {
    id: 'st-nyc-01',
    name: 'Manhattan Mid-Town Energy Plaza',
    operator: 'ChargePoint Global',
    networkId: 'net-chargepoint',
    latitude: 40.7549,
    longitude: -73.9840,
    country: 'United States',
    city: 'New York',
    address: '600 5th Ave, New York, NY 10020',
    openingHours: '24/7 Open',
    status: 'AVAILABLE',
    amenities: ['Coffee Shop', 'WiFi', 'Valet Parking', 'Restrooms'],
    rating: 4.7,
    reviewsCount: 420,
    dataSource: 'LIVE',
    providerName: 'ChargePoint Open API',
    lastUpdated: '4 min ago',
    connectors: [
      { id: 'c-nyc-1', stationId: 'st-nyc-01', type: 'CCS2', powerKw: 150, status: 'AVAILABLE', pricePerKwh: 0.48, currency: 'USD' },
      { id: 'c-nyc-2', stationId: 'st-nyc-01', type: 'NACS', powerKw: 250, status: 'BUSY', pricePerKwh: 0.48, currency: 'USD' },
      { id: 'c-nyc-3', stationId: 'st-nyc-01', type: 'CCS2', powerKw: 150, status: 'AVAILABLE', pricePerKwh: 0.48, currency: 'USD' },
    ],
  },
  {
    id: 'st-tky-01',
    name: 'Shibuya Crossing EV Superstation',
    operator: 'Tesla Supercharger',
    networkId: 'net-supercharger',
    latitude: 35.6595,
    longitude: 139.7004,
    country: 'Japan',
    city: 'Tokyo',
    address: '2 Chome-21-1 Dogenzaka, Shibuya City, Tokyo 150-0043',
    openingHours: '24/7 Open',
    status: 'AVAILABLE',
    amenities: ['Convenience Store', 'Coffee Shop', 'High-Speed WiFi', 'Underground Bay'],
    rating: 4.9,
    reviewsCount: 350,
    dataSource: 'LIVE',
    providerName: 'Tesla Asia-Pacific Adapter',
    lastUpdated: '2 min ago',
    connectors: [
      { id: 'c-tky-1', stationId: 'st-tky-01', type: 'NACS', powerKw: 250, status: 'AVAILABLE', pricePerKwh: 75, currency: 'JPY' },
      { id: 'c-tky-2', stationId: 'st-tky-01', type: 'CHAdeMO', powerKw: 150, status: 'AVAILABLE', pricePerKwh: 70, currency: 'JPY' },
      { id: 'c-tky-3', stationId: 'st-tky-01', type: 'CCS2', powerKw: 150, status: 'AVAILABLE', pricePerKwh: 70, currency: 'JPY' },
    ],
  },
  {
    id: 'st-ber-01',
    name: 'Alexanderplatz Schnellladestation',
    operator: 'Ionity Ultra Fast',
    networkId: 'net-ionity',
    latitude: 52.5219,
    longitude: 13.4132,
    country: 'Germany',
    city: 'Berlin',
    address: 'Alexanderstraße 7, 10178 Berlin',
    openingHours: '24/7 Open',
    status: 'AVAILABLE',
    amenities: ['Bistro', 'Free WiFi', 'Solar Roof', 'Restroom'],
    rating: 4.85,
    reviewsCount: 210,
    dataSource: 'LIVE',
    providerName: 'Ionity DACH Adapter',
    lastUpdated: '1 min ago',
    connectors: [
      { id: 'c-ber-1', stationId: 'st-ber-01', type: 'CCS2', powerKw: 350, status: 'AVAILABLE', pricePerKwh: 0.69, currency: 'EUR' },
      { id: 'c-ber-2', stationId: 'st-ber-01', type: 'CCS2', powerKw: 350, status: 'AVAILABLE', pricePerKwh: 0.69, currency: 'EUR' },
    ],
  },
  {
    id: 'st-syd-01',
    name: 'Circular Quay Harbour EV Hub',
    operator: 'ChargePoint Global',
    networkId: 'net-chargepoint',
    latitude: -33.8617,
    longitude: 151.2101,
    country: 'Australia',
    city: 'Sydney',
    address: 'Macquarie St, Sydney NSW 2000',
    openingHours: '24/7 Open',
    status: 'AVAILABLE',
    amenities: ['Waterfront Café', 'Restrooms', 'WiFi', 'Park Views'],
    rating: 4.9,
    reviewsCount: 165,
    dataSource: 'LIVE',
    providerName: 'ChargePoint APAC Adapter',
    lastUpdated: '4 min ago',
    connectors: [
      { id: 'c-syd-1', stationId: 'st-syd-01', type: 'CCS2', powerKw: 175, status: 'AVAILABLE', pricePerKwh: 0.65, currency: 'AUD' },
      { id: 'c-syd-2', stationId: 'st-syd-01', type: 'Type 2', powerKw: 22, status: 'AVAILABLE', pricePerKwh: 0.40, currency: 'AUD' },
    ],
  },
];

export const PRELOADED_VEHICLES: Vehicle[] = [
  // Tesla
  { id: 'veh-01', brand: 'Tesla', model: 'Model Y Long Range', batteryCapacityKwh: 75, rangeKm: 533, connectorType: 'CCS2', maxChargeRateKw: 250, isDefault: true },
  { id: 'veh-02', brand: 'Tesla', model: 'Model 3 Performance', batteryCapacityKwh: 82, rangeKm: 547, connectorType: 'NACS', maxChargeRateKw: 250 },
  { id: 'veh-03', brand: 'Tesla', model: 'Model S Plaid', batteryCapacityKwh: 100, rangeKm: 637, connectorType: 'NACS', maxChargeRateKw: 250 },
  { id: 'veh-04', brand: 'Tesla', model: 'Cybertruck Tri-Motor', batteryCapacityKwh: 123, rangeKm: 515, connectorType: 'NACS', maxChargeRateKw: 250 },

  // Tata Motors (India)
  { id: 'veh-05', brand: 'Tata', model: 'Nexon EV Max Long Range', batteryCapacityKwh: 40.5, rangeKm: 453, connectorType: 'CCS2', maxChargeRateKw: 50 },
  { id: 'veh-06', brand: 'Tata', model: 'Punch EV Long Range', batteryCapacityKwh: 35, rangeKm: 421, connectorType: 'CCS2', maxChargeRateKw: 50 },
  { id: 'veh-07', brand: 'Tata', model: 'Curvv EV 55', batteryCapacityKwh: 55, rangeKm: 585, connectorType: 'CCS2', maxChargeRateKw: 70 },
  { id: 'veh-08', brand: 'Tata', model: 'Tiago EV Long Range', batteryCapacityKwh: 24, rangeKm: 315, connectorType: 'CCS2', maxChargeRateKw: 25 },

  // Hyundai & Kia
  { id: 'veh-09', brand: 'Hyundai', model: 'Ioniq 5 AWD', batteryCapacityKwh: 77.4, rangeKm: 481, connectorType: 'CCS2', maxChargeRateKw: 235 },
  { id: 'veh-10', brand: 'Hyundai', model: 'Ioniq 6 Long Range', batteryCapacityKwh: 77.4, rangeKm: 614, connectorType: 'CCS2', maxChargeRateKw: 235 },
  { id: 'veh-11', brand: 'Kia', model: 'EV6 GT AWD', batteryCapacityKwh: 77.4, rangeKm: 424, connectorType: 'CCS2', maxChargeRateKw: 235 },
  { id: 'veh-12', brand: 'Kia', model: 'EV9 Land AWD', batteryCapacityKwh: 99.8, rangeKm: 505, connectorType: 'CCS2', maxChargeRateKw: 210 },

  // Porsche & Audi
  { id: 'veh-13', brand: 'Porsche', model: 'Taycan Turbo S', batteryCapacityKwh: 93.4, rangeKm: 450, connectorType: 'CCS2', maxChargeRateKw: 270 },
  { id: 'veh-14', brand: 'Porsche', model: 'Macan Electric Turbo', batteryCapacityKwh: 100, rangeKm: 591, connectorType: 'CCS2', maxChargeRateKw: 270 },
  { id: 'veh-15', brand: 'Audi', model: 'RS e-tron GT', batteryCapacityKwh: 93.4, rangeKm: 472, connectorType: 'CCS2', maxChargeRateKw: 270 },
  { id: 'veh-16', brand: 'Audi', model: 'Q8 e-tron 55', batteryCapacityKwh: 114, rangeKm: 600, connectorType: 'CCS2', maxChargeRateKw: 170 },

  // BMW & Mercedes-Benz
  { id: 'veh-17', brand: 'BMW', model: 'i4 eDrive40', batteryCapacityKwh: 83.9, rangeKm: 590, connectorType: 'CCS2', maxChargeRateKw: 205 },
  { id: 'veh-18', brand: 'BMW', model: 'i7 xDrive60', batteryCapacityKwh: 101.7, rangeKm: 625, connectorType: 'CCS2', maxChargeRateKw: 195 },
  { id: 'veh-19', brand: 'Mercedes-Benz', model: 'EQS 580 4MATIC', batteryCapacityKwh: 107.8, rangeKm: 770, connectorType: 'CCS2', maxChargeRateKw: 200 },
  { id: 'veh-20', brand: 'Mercedes-Benz', model: 'EQE 350+', batteryCapacityKwh: 90.6, rangeKm: 660, connectorType: 'CCS2', maxChargeRateKw: 170 },

  // MG & Mahindra
  { id: 'veh-21', brand: 'MG', model: 'ZS EV Exclusive', batteryCapacityKwh: 50.3, rangeKm: 461, connectorType: 'CCS2', maxChargeRateKw: 50 },
  { id: 'veh-22', brand: 'MG', model: 'Windsor EV 38', batteryCapacityKwh: 38, rangeKm: 331, connectorType: 'CCS2', maxChargeRateKw: 45 },
  { id: 'veh-23', brand: 'Mahindra', model: 'XUV400 EL Pro', batteryCapacityKwh: 39.4, rangeKm: 456, connectorType: 'CCS2', maxChargeRateKw: 50 },

  // BYD
  { id: 'veh-24', brand: 'BYD', model: 'Seal Performance AWD', batteryCapacityKwh: 82.56, rangeKm: 570, connectorType: 'CCS2', maxChargeRateKw: 150 },
  { id: 'veh-25', brand: 'BYD', model: 'Atto 3 Extended', batteryCapacityKwh: 60.48, rangeKm: 521, connectorType: 'CCS2', maxChargeRateKw: 80 },

  // Rivian, Lucid, Volvo, Ford
  { id: 'veh-26', brand: 'Rivian', model: 'R1T Dual-Motor', batteryCapacityKwh: 135, rangeKm: 560, connectorType: 'NACS', maxChargeRateKw: 220 },
  { id: 'veh-27', brand: 'Lucid', model: 'Air Grand Touring', batteryCapacityKwh: 112, rangeKm: 830, connectorType: 'CCS2', maxChargeRateKw: 300 },
  { id: 'veh-28', brand: 'Volvo', model: 'EX90 Twin Motor', batteryCapacityKwh: 111, rangeKm: 600, connectorType: 'CCS2', maxChargeRateKw: 250 },
  { id: 'veh-29', brand: 'Ford', model: 'Mustang Mach-E GT', batteryCapacityKwh: 91, rangeKm: 490, connectorType: 'CCS2', maxChargeRateKw: 150 },
];

export const MOCK_NOTIFICATIONS: UserNotification[] = [
  {
    id: 'notif-1',
    title: 'Charging Completed',
    message: 'Your Tesla Model Y finished charging to 80% at Mayfair Ultra-Fast Power Hub.',
    timestamp: '10 mins ago',
    read: false,
    type: 'SESSION',
  },
  {
    id: 'notif-2',
    title: 'Station Available',
    message: 'Guindy Industrial Tech Hub has 2 ultra-fast 150 kW bays available now.',
    timestamp: '1 hour ago',
    read: false,
    type: 'STATION',
  },
  {
    id: 'notif-3',
    title: 'Trip Plan Ready',
    message: 'Your Chennai to Bengaluru route plan has 2 scheduled charging stops optimized for battery health.',
    timestamp: '2 hours ago',
    read: true,
    type: 'TRIP',
  },
];

export const MOCK_HISTORY: ChargingHistoryEntry[] = [
  {
    id: 'hist-01',
    date: '2026-10-06',
    stationName: 'Mayfair Ultra-Fast Power Hub',
    city: 'London',
    energyKwh: 44.5,
    durationMins: 22,
    cost: 30.70,
    currency: 'GBP',
    status: 'COMPLETED',
  },
  {
    id: 'hist-02',
    date: '2026-10-02',
    stationName: 'Downtown Dubai Mall Energy Plaza',
    city: 'Dubai',
    energyKwh: 52.0,
    durationMins: 25,
    cost: 65.00,
    currency: 'AED',
    status: 'COMPLETED',
  },
  {
    id: 'hist-03',
    date: '2026-09-28',
    stationName: 'Guindy Industrial Tech Charging Hub',
    city: 'Chennai',
    energyKwh: 38.2,
    durationMins: 28,
    cost: 802.20,
    currency: 'INR',
    status: 'COMPLETED',
  },
];
